name: flutter_localization
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  intl: any
  http: any
  shared_preferences:  any
  provider:  any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  # assets:
  #   - images/
